### ISSUE TITLE
Build submit petitions flow

### ISSUE THREAD

**Issue by christopherlim98** [opengovsg/petitionsgovsg#20]
Citizens need to submit a petition. Below each question section, we should have a section below guiding them on the contents to write.

Petitions flow:
1. click "Submit Petition" from landing page
2. go into create petitions page
 
**Section 1**
- **Petition Title** (<50 characters)
- [Optional] Which ministry is most relevant to your petition? 

**Section 2**
As the petition submitter, your name will be attached to this petition.
- [NO EDIT] Full name
- [Optional] Introduce a little more about who you are for this petition

**Section 3**
- What do you want us to do? – <3000 characters, rich text (bold, italics, link, newline, point, numbering – separate issue)

**Section 4**
- Why do you want this? – < 3000 characters, rich text (bold, italics, link, newline, point, numbering – separate issue) 

**Section 5**
- [Optional] Are there further references to support your petition? E.g. data, papers, relevant government policy, news articles

**Preview**

3. Preview petition

4. Submit

5. Congrats on pushing for change **modal**
- share on social media / view on main page

Example from change.org
![image](https://user-images.githubusercontent.com/21275222/149365573-7a7331cc-c80d-4472-8558-ceff52bd2a0a.png)

[Petitions rough sketches
](https://www.figma.com/file/rPG1by0JGEfoctDLYk0nxK/Petitions-Working?node-id=4%3A15)

**Comment by aidenywl** [comment]
Added user story + reformatted issue, added fields, flow, figma sketch link.

**Comment by christopherlim98** [comment]
Closed by #109
