### ISSUE TITLE
Use local dev proxy for text/html requests

### ISSUE THREAD

**Issue by christopherlim98** [opengovsg/petitionsgovsg#248]
**Is your feature request related to a problem? Please describe.**
Currently, SGID login is invoked by redirecting the user to the SGID endpoint by changing `location.href`. 
For local development, this means that we redirect the user to `localhost:6174` instead of `localhost:3000`.

**Describe the solution you'd like**
Ideally, we should be able to have a proxy that redirects from `localhost:3000` to `localhost:6174` even for text/html requests. Currently, CRA has a built-in proxy that redirects api requests to a specified proxy (i.e. 6174) as a fallback. However, these redirects do not apply to `text/html` out of the box.

Read more: https://create-react-app.dev/docs/proxying-api-requests-in-development/

**Comment by LoneRifle** [comment]
Literature review - https://create-react-app.dev/docs/proxying-api-requests-in-development/#configuring-the-proxy-manually
