### ISSUE TITLE
Create Landing Page

### ISSUE THREAD

**Issue by aidenywl** [opengovsg/petitionsgovsg#33]
Rough outline:

**Landing page + tagline** 
**Start a petition button**
**Explanation of how petition works**
1. Submit petition
2. Garner signatures
3. Petition submitted to ministry for a response
****
![image](https://user-images.githubusercontent.com/21275222/149368594-2af2d4cf-7dc4-4da0-80cd-e0cac0bb95a4.png)

**Comment by christopherlim98** [comment]
Closed by #76
