### ISSUE TITLE
About View

### ISSUE THREAD

**Issue by aidenywl** [opengovsg/petitionsgovsg#37]
Citizens need to have a transparent view of the process and background behind the process to feel comfortable.

1. About:
PetitionsSG is an initiative by Open Government Products, GovTech and REACH, the Singapore government's feedback unit. This platform enables citizens to engage and advocate for ground-up causes on a legitimate platform. Petitions above 10,000 signatures will be submitted to the relevant ministry for a response.

2. How petitions work
3. Standards for petitions
4. Parliamentary Petitions
- explain how this differs from the existing parliamentary petitions process, is not meant to replace it, but augment it.

**Comment by christopherlim98** [comment]
Closed by #123
