### ISSUE TITLE
Anonymous signing process on the backend

### ISSUE THREAD

**Issue by aidenywl** [opengovsg/petitionsgovsg#64]
Some citizens who sign petitions will want to remain completely anonymous where even in the event of a data leak, the petitions they signed cannot be traced back to their personal details.

However, it must be implemented in a way that prevents duplicate signing of signatures.

Idea floated by @christopherlim98, subject to change:
- [ ] When a petition is signed anonymously, their sgID id is hashed with a unique salt for each petition, preventing backward tracing to the user or tracing across petitions.
- [ ] When a petition is signed with the full name, their original sgID is used instead.

**Comment by christopherlim98** [comment]
Closed by #19 , #157
