### ISSUE TITLE
Seconder system before petition is published

### ISSUE THREAD

**Issue by aidenywl** [opengovsg/petitionsgovsg#65]
Ministries and REACH want a process to cut down the number of petitions that are not meaningful or well written.
- [ ] Immediately after petition submission, petition is not published on the main website
- [ ] Immediately after petition submission, petition is not indexed on a search engine
- [ ] 3 Seconder signatures are required before the petition is made public, these signatures must have their full legal names attached.

**Priority:**
P2 for hackathon, P1 before public release.

**Comment by christopherlim98** [comment]
Closed by #125
